### ISSUE TITLE
Diamond of Rombhus: rooms 30 and 33

### ISSUE THREAD

**Issue by Roelofpieter** [kesiev/stampadia#4]
Hello. I printed and played my first Stampadia dungeon yesterday. I managed to find the three diamond parts and defeat the boss, although I had to make use of the Resurrection scroll. Very enjoyable game. Thank you very much for creating this. I watched the YouTube video also which was very explanatory. I did have some trouble understanding the "Gain one HP" mechanism, but going though the manual again I saw it was literally right there. Oops :-)

Anyhow, I just thought I´d make a comment on the room instructions for room 30. It says that you can go to anywhere in room 33. But by that time you can't have discovered this room yet (I think). This is no biggy by any means, but it may be a little glitch in the algorithm, so it may be in a future scenario.

I think the line should read: _Move [1] **& x33** » You vanish into thin air, move anywhere in room 33_
And room 33 should then read: Move [1] » _You feel dizzy, move anywhere in room 30, **x33**_

Hope this makes sense. Meanwhile I see a new adventure available. Saviour's Curse!, here I come!

Thanks again,
Rolf

**Comment by kesiev** [comment]
First, thank you for your kind words and enthusiasm!

So, to the issue. In Stampadia world you'll find many teleports to other rooms. They may be shortcuts to unexplored rooms, so you can use them to save gold while leaving the dungeons (and that's the teleport you've found), one-way teleports and... well... No spoilers.

The teleport of Diamond of Rombhus is working this way: On room 30, you vanish in any space of room 33 - draw the room even in the middle of nowhere and place the hero token anywhere. The same goes for room 33. :) Since your hero entered a new room, once teleported you've to read the room description.

Probably I should update the manual explaining that's may happen. I'm leaving this issue opened.

**Comment by kesiev** [comment]
I've added your question to the new online [Learn](https://www.kesiev.com/stampadia/learn.html) section of Stampadia. If you've more questions about the rules or talk about Stampadia in general, you can join us on [Discord](https://discord.com/invite/EDYP2N4RMn)
